version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5431:5432"
    volumes:
      - /home/postgres:/var/lib/postgresql/data 
