version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - /home/postgres:/var/lib/postgresql/data 
